# Generated by Django 5.2.7 on 2026-05-22 07:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceRecording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id_anonymous', models.CharField(blank=True, default='', max_length=100)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='voice_recordings/%Y/%m/')),
                ('audio_size_bytes', models.IntegerField(default=0)),
                ('audio_format', models.CharField(default='webm', max_length=10)),
                ('transcription', models.TextField(blank=True, default='')),
                ('transcription_success', models.BooleanField(default=False)),
                ('error_message', models.CharField(blank=True, default='', max_length=500)),
                ('selected_language', models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Malayalam', 'Malayalam'), ('Tamil', 'Tamil'), ('Telugu', 'Telugu'), ('Kannada', 'Kannada')], default='English', max_length=20)),
                ('detected_language', models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Malayalam', 'Malayalam'), ('Tamil', 'Tamil'), ('Telugu', 'Telugu'), ('Kannada', 'Kannada')], default='English', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_recordings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voice Recording',
                'verbose_name_plural': 'Voice Recordings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='api_voicere_created_2625c9_idx'), models.Index(fields=['user'], name='api_voicere_user_id_46c512_idx'), models.Index(fields=['transcription_success'], name='api_voicere_transcr_bb0df1_idx')],
            },
        ),
    ]
