# Generated by Django 5.2.7 on 2026-02-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_healthactivity_healthgoal_healthreport_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="allergies",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="blood_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                ],
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="chronic_conditions",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="customuser",
            name="current_medications",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="emergency_contact_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="customuser",
            name="emergency_contact_number",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="height",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Height in cm",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="medical_history",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="pincode",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="customuser",
            name="state",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="customuser",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Weight in kg",
                max_digits=5,
                null=True,
            ),
        ),
    ]
