# Generated by Django 5.2.7 on 2026-02-08 17:50

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_customuser_allergies_customuser_blood_group_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorRating",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        help_text="Rating from 1 to 5 stars",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "review",
                    models.TextField(blank=True, help_text="Optional written review"),
                ),
                (
                    "pros",
                    models.TextField(blank=True, help_text="What the patient liked"),
                ),
                (
                    "cons",
                    models.TextField(blank=True, help_text="Areas for improvement"),
                ),
                ("would_recommend", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rating",
                        to="api.appointment",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="api.doctorprofile",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_ratings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["doctor", "-created_at"],
                        name="api_doctorr_doctor__4fae91_idx",
                    ),
                    models.Index(
                        fields=["patient", "-created_at"],
                        name="api_doctorr_patient_0483eb_idx",
                    ),
                ],
                "unique_together": {("doctor", "patient", "appointment")},
            },
        ),
    ]
