# Generated by Django 5.2.7 on 2026-06-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_medicine_image_url_medicineimage_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationreminder',
            name='email_reminders_enabled',
            field=models.BooleanField(default=False, help_text='Send email reminders to patient at each scheduled time slot'),
        ),
        migrations.AddField(
            model_name='medicationreminder',
            name='meal_timing',
            field=models.CharField(blank=True, choices=[('before', 'Before Meals'), ('after', 'After Meals'), ('with', 'With Meals'), ('anytime', 'Anytime')], default='', max_length=20),
        ),
    ]
