# Generated by Django 5.2.7 on 2026-07-08 05:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_labtest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('pharmacist', 'Pharmacist'), ('ashaworker', 'ASHA Worker'), ('admin', 'Admin')], default='patient', max_length=20),
        ),
        migrations.CreateModel(
            name='AshaProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('village_name', models.CharField(max_length=100)),
                ('block_name', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('government_id', models.CharField(max_length=50, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asha_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='assigned_asha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_patients', to='api.ashaprofile'),
        ),
        migrations.CreateModel(
            name='PointOfCareTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_type', models.CharField(max_length=100)),
                ('results', models.JSONField(default=dict)),
                ('test_strip_image', models.ImageField(blank=True, null=True, upload_to='poct_tests/')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asha_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorded_poct_tests', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poct_tests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
