# Generated by Django 5.2.7 on 2026-07-08 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_customuser_user_type_ashaprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestbooking',
            name='assigned_technician',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'laboratory'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labtestbooking',
            name='collected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtestbooking',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='lab_reports/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('pharmacist', 'Pharmacist'), ('ashaworker', 'ASHA Worker'), ('laboratory', 'Laboratory Staff'), ('admin', 'Admin')], default='patient', max_length=20),
        ),
        migrations.AlterField(
            model_name='labtestbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('collected', 'Sample Collected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
